### PR TITLE
ci: Fix the failing build

### PR DESCRIPTION
**Pull request by seanpoulter**
### TODO

- [x] Check if the tests pass with the standalone test skipped
- [ ] Extract the standalone test. They hypothesis is that we're trying to start ChromeDriver twice.

### Proposed Changes

Fix the failing CI build by:

* TODO

### CODE REVIEW

**Comment by tehhowch** [comment]
I don't believe the test skip is necessary

**Comment by seanpoulter** [comment]
Ah, yes, sorry! This is a WIP. The plan is to split out the test script to run the standalone tests separately from the rest so we don't end up with an ETXBUSY from ChromeDriver running twice. Christian suggested running them sequentially with `npm-run-all` like other repos.

**Comment by tehhowch** [comment]
Oh, there's no reason to even bother with the actual standalone mode in this service's unit tests. I've updated that single test to make it plain what is being done.

**Comment by seanpoulter** [comment]
Thanks @tehhowch! That fixes the failing CI build.

**Pull request closed without merging**
